### ISSUE TITLE
Summary for protected pages

### ISSUE THREAD

**Issue by poornimanayar** [skttl/umbraco-fulltextsearch8#109]
I noticed that I cannot get a summary for protected pages even if I am logged in. Is that by default?

**Comment by enkelmedia** [comment]
@poornimanayar What you you mean with a "summary"? Can you be a little more specific? No data added to the Examine index? 

What version of Full Text Search are you on?

In the latest alpha-releases rendering is performed with a regular HTTP-client which would require authentication if the page require this.
