### ISSUE TITLE
Add logging for debugging

### ISSUE THREAD

**Issue by enkelmedia** [skttl/umbraco-fulltextsearch8#111]
Hi!

I just want to check before creating a PR.

I would like to add some more logging to make debugging easier, for example in our test/Q&A-environments there is special requirements for the HttpClient to be able to render the pages since they are protected. At the moment it will only be a empty string but it's hard to know why.

I'm thinking that we can add something like this:

![image](https://github.com/skttl/umbraco-fulltextsearch8/assets/1782524/818a308a-4395-408d-a3ba-a9f87368a5a6)

Making sure that we use `_logger.IsEnabled()` to avoid boxing when the log-level is not enabled.

I'm wondering:

## 1. Is this a good idea?
I think so =D

## 2. What log level(s) should we use? 
I think that we should use "debug" to indicate things that are truly debug. Like which URL we're trying to fetch etc. But maybe use information when the page returns something other than 200?

Let me know and I'll create a PR.

**Comment by skttl** [comment]
Didn't even know that `IsEnabled` function, but after reading about it shortly, it sounds like a good idea, especially if we end up adding lots of debug messages :)

I think messages like these should be debug, also the information you have further down.

**Comment by enkelmedia** [comment]
Hi!

I've read about it and it saves some of the boxing when the parameters are boxed so I guess it avoids som allocations id the call is not needed. I've noticed that they use it in Core in some placed.

I'll create a PR an keep it all on Debug-level - I agree it's sometimes annoying to get the log filled with random "stuff"

=D
