### ISSUE TITLE
Split C# stuff into a Core nuget package

### ISSUE THREAD

**Issue by stefankip** [skttl/umbraco-fulltextsearch8#13]
I have my models in a seperate project (class library) and I'd like to reference the interfaces of the models in the FullTextSearch package. It would be nice if a Core nuget package existed with only the c# stuff.

**Comment by skttl** [comment]
Hi @stefankip 

After moving to RCL do you still think this is worth?

**Comment by skttl** [comment]
@timeverts there is no App_Plugins bloat in v3, because of the RCL. That's why I'm curious if there is any benefits in splitting up now.

**Comment by skttl** [comment]
v2 is likely not getting any updates from now. Focusing on latest version.
