### ISSUE TITLE
Running on Umbraco Cloud

### ISSUE THREAD

**Issue by stefankip** [skttl/umbraco-fulltextsearch8#26]
I deployed a project using this package and it doesn't work on Umbraco Cloud.
The error:
```
System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at Our.Umbraco.FullTextSearch.Services.HtmlService.GetHtmlByUrl(String url, String& fullHtml)
```

This is obvious, because the cloud environment is protected using Basic authentication. So we need to figure out how we can circumvent this in the best possible way.
One option would be to add username and password to the appSettings and use them with the webrequests.

**Comment by skttl** [comment]
You are right in regards to non-public environments. Once you go live, it works fine. Another approach could be to whitelist the servers own ip.
