### ISSUE TITLE
Only index nodes with a template and check umbracoNaviHide

### ISSUE THREAD

**Issue by stefankip** [skttl/umbraco-fulltextsearch8#27]
https://github.com/skttl/Our.Umbraco.FullTextSearch/blob/8ef476dc69d02fb2bb632d2ce1d67946393c80c3/src/Our.Umbraco.FullTextSearch/Services/CacheService.cs#L40

Only nodes with a template and umbracoNaviHide = null or false should be indexed I think.

**Comment by stefankip** [comment]
@skttl penny for your thoughts?

**Comment by skttl** [comment]
Yes, no-template nodes should be fine to filter out.

I also agree that having null or false in umbracoNaviHide shouldn't exclude from indexing, but isn't that how it already is?

**Comment by stefankip** [comment]
Ah yes there is the `FullTextSearch.DisallowedPropertyAliases` setting ofcourse. I think it's not working for me though, but I'll have to look into it.

**Comment by skttl** [comment]
IIRC the DisallowedPropertyAliases is only used when searching. It will index anyway :) You could probably add that to the caching filter.

Maybe even the caching service should handle removing FullText content, if template is removed or DisallowedPropertyAliases is set to false.

**Comment by stefankip** [comment]
I'll look into it!

**Comment by skttl** [comment]
```Maybe even the caching service should handle removing FullText content, if template is removed or DisallowedPropertyAliases is set to false.```

Just tried adding a disallowed property, and setting it on an existing node. It got removed from the index as expected :)

**Comment by stefankip** [comment]
@skttl did you implement the template check?

**Comment by skttl** [comment]
Ah sorry, thought it was already in, since I got the node removed from the index.

But then it is probably a case of the url not returning anything, resulting in the node being removed.

**Comment by tanteemmie** [comment]
The search still includes results from a type without a template. So this is not working yet.

**Comment by skttl** [comment]
I made some fixes in the latest commits, making sure that the node is removed from both the cache and its Full Text Content is removed from the index. Closing this then :)
