### ISSUE TITLE
Switch to using RenderTemplate() for getting the content

### ISSUE THREAD

**Issue by skttl** [skttl/umbraco-fulltextsearch8#36]
I just got RenderTemplate() working, which can make the Http Requests for getting content obsolete. I want to switch the indexing to only use RenderTemplate.

Preliminary testing shows that the caching of content can be done without much delay already in the publish event, in stead of adding a task that should be done moments later in the background.

Besides, not relying on the server being able to call itself is a bonus.

Any comments?

**Comment by skttl** [comment]
This would also make it work in Umbraco cloud dev environments #26

**Comment by skttl** [comment]
And it would make fixing #11 unnecessary

**Comment by TimGeyssens** [comment]
nice!

**Comment by TimGeyssens** [comment]
Makes sense to use rendertemplate instead of scraping...so yes, go for it!

**Comment by skttl** [comment]
Work has begun :) https://github.com/skttl/umbraco-fulltextsearch8/commit/dbbf2188bfc52f0befd759c97c2da44dec8fcd79

**Comment by TimGeyssens** [comment]
Boom MVP 2021 :p

**Comment by stefankip** [comment]
Very nice improvement @skttl!

**Comment by TimGeyssens** [comment]
Any ideas on the speed improvements? Since now without webclient it must be faster

**Comment by skttl** [comment]
No idea, and it's not directly comparable, as the http request were done in a background thread.

So you could say, that there is a speed improvement in up to 1 minute, as the http request caching was done every minute :)

**Comment by TimGeyssens** [comment]
sweet!
