### ISSUE TITLE
Add scheduled reindexing

### ISSUE THREAD

**Issue by skttl** [skttl/umbraco-fulltextsearch8#38]
I would like a way to have scheduled indexing of specific (or all) nodes in the background.

For pages including content from other sources, relying on publish events to index is not enough. 

I'm thinking a config like in unversion where you can specify an optional content type alias or xpath expression, in addition to a max age would be could. 

A background task running every few minutes could then search the index through for nodes indexed earlier than the max age and reindex them. 

The xpath option would have to use the content cache I guess, thus probably be a bit more expensive though. 

Comments are welcome 🙂

**Comment by TimGeyssens** [comment]
Instead of scheduled reindexing would an option be to just add docs on how to reindex a node that has third party data on the frontend... (Just thinking)

**Comment by skttl** [comment]
I'll probably drop this idea, and do some documentation on how to do it instead :)
