### ISSUE TITLE
Add Helper methods for searching

### ISSUE THREAD

**Issue by skttl** [skttl/umbraco-fulltextsearch8#39]
To make it easier for non c# devs to use the package, I would like to add some static helper methods for searching.

Thinking of one very simple one, that uses the defaults, and just allows for specifying search terms, current page number and culture, and a more specific one, where you would have to supply a `Search` object and the current page (similar to the `Search` method in `ISearchService`.

Currently I have the following code ready:

```cs
        public static IFullTextSearchResult Search(string searchTerms, string culture = null, int currentPage = 1)
        {
            if (!(Current.Factory.TryGetInstance(typeof(ISearchService)) is ISearchService searchService)) return null;

            currentPage = currentPage < 1 ? 1 : currentPage;

            var search = new Search(searchTerms);

            if (!culture.IsNullOrWhiteSpace())
                search = search.SetCulture(culture);

            return searchService.Search(search, currentPage);
        }

        public static IFullTextSearchResult Search(Search search, int currentPage = 1)
        {
            if (!(Current.Factory.TryGetInstance(typeof(ISearchService)) is ISearchService searchService)) return null;

            currentPage = currentPage < 1 ? 1 : currentPage;

            return searchService.Search(search, currentPage);
        }
```

Comments are welcome :)

**Comment by skttl** [comment]
Work has begun :) https://github.com/skttl/umbraco-fulltextsearch8/commit/dbbf2188bfc52f0befd759c97c2da44dec8fcd79

**Comment by Sven883** [comment]
Hey @skttl  - Would it be best practice to use             
`if (!(Current.Factory.TryGetInstance(typeof(ISearchService)) is ISearchService searchService)) return null;`
instead of
`var searchService = DependencyResolver.Current.GetService<ISearchService>();`

Thanks!

**Comment by skttl** [comment]
Best practise would be to inject in your controller. You should post these questions at our.umbraco.com instead.
