### ISSUE TITLE
Empty exception on reindexing

### ISSUE THREAD

**Issue by stefankip** [skttl/umbraco-fulltextsearch8#49]
I just updated to v1.1.1 via NuGet and found out the `App_Plugins/Our.Umbraco.FullTextSearch/` was empty, so I copied it manually.

But this issue is really about this:
![image](https://user-images.githubusercontent.com/46313552/101830702-35644000-3b35-11eb-9fc9-7d3c87993f2e.png)

When I re-index I get this empty exception without any info, neither in the logs.

**Comment by skttl** [comment]
I've seen this before when saving nodes. Are any of your nodes giving ysods in the frontend?

**Comment by stefankip** [comment]
That might be the case, but shouldn't impact this process right?

**Comment by skttl** [comment]
Check out #47. It might be the same problem.

**Comment by skttl** [comment]
Also fixed in 1.2.0-beta (https://github.com/skttl/umbraco-fulltextsearch8/releases/tag/release%2F1.2.0-beta)

**Comment by stefankip** [comment]
@skttl this is still happening in my case with 1.2.x beta.
