### ISSUE TITLE
Style tag isn't stripped from the index

### ISSUE THREAD

**Issue by stefankip** [skttl/umbraco-fulltextsearch8#50]
These are my config settings regarding the `XpathsToRemove`:
```
<XpathsToRemove>
  <add>//head</add>
  <add>//script</add>
  <add>//style</add>
  <add>//footer</add>
  <add>//nav</add>
  <add>//*[@id='cookie-bar']</add>
  <add>//*[@id='search-bar']</add>
</XpathsToRemove>
```

And I have this in my Layout view:
```
<head>
    [...]
    <style type="text/css">
        .honing {
            display: none;
        }
    </style>
    [...]
</head>
```

In my index this isn't removed, for example from the `FullTextCache` DB table:

```
Nieuws | Websitename .honing {
display: none;
}
Edit Wij geven om privacy Daarom gebruiken we functionele en analytische cookies voor website optimalisatie. Geef hiervoor je voorkeuren op: Ja, ik wil analytische cookies Ja, ik wil marketing cookies Voorkeuren opslaan
<page text>
Disclaimer Algemene voorwaarden Cookies (function () {
var s = document.createElement("script"); s.type = "text/javascript"; s.async = true; s.src = '//api.usersnap.com/load/sdfsdfsdfsdfdsfsdfdsfdssdffsdfsd.js';
var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(s, x);
})();
```

Looking at it, it seems it's not the only tag not being remove, for example the usersnap `script` at the end.

**Comment by skttl** [comment]
Seems like a great case for adding some unit tests :)

**Comment by stefankip** [comment]
Haha yeah it is :-D

**Comment by skttl** [comment]
Would love to add some tests for this, but I don't know if it's possible without refactoring the config?

The config class is reading from `HttpRuntime.AppDomainAppPath + "App_Plugins\FullTextSearch\FullTextSearch.config"`, I guess this isn't really testable, am I right?

**Comment by skttl** [comment]
Hi @stefankip 

What version are you seeing this in? Just trying it out on the latest source, and it seems to work - at least here :)

**Comment by skttl** [comment]
I put up a 1.2.0-beta on Nuget (https://github.com/skttl/umbraco-fulltextsearch8/releases/tag/release%2F1.2.0-beta)

Can you try with that, and see if the tag stripping works?

**Comment by stefankip** [comment]
Awesome! Yes I'll try on Monday 😁

**Comment by stefankip** [comment]
The content of the style tag is still indexed with 1.2.0 beta.

**Comment by skttl** [comment]
Weird, it works for me. Any chance you could share your view and config file?

**Comment by stefankip** [comment]
Let me do a quick debug session 😊

**Comment by stefankip** [comment]
Mate, my config isn't used at all 🤣

https://github.com/skttl/umbraco-fulltextsearch8/blob/develop/src/Our.Umbraco.FullTextSearch/Services/FullTextSearchConfig.cs#L39

**Comment by stefankip** [comment]
Probably also the reason why this wasn't working for me as well 😂

https://github.com/skttl/umbraco-fulltextsearch8/issues/27#issuecomment-635244705

**Comment by skttl** [comment]
oops :) better fix the docs :)

**Comment by stefankip** [comment]
Isn't the correct path `App_Plugins/Our.Umbraco.FullTextSearch/FullTextSearch.config` instead of the one used in config right now?

**Comment by skttl** [comment]
No the App_Plugins folder is called `FullTextSearch` so the docs is wrong. But you can override the config file path through the appSetting `FullTextSearch.ConfigPath`

**Comment by stefankip** [comment]
Okay, I'll just jump on the bandwagon and go with the default ;-)
