### ISSUE TITLE
FullTextContent Empty

### ISSUE THREAD

**Issue by Sven883** [skttl/umbraco-fulltextsearch8#59]
Hello!

Any idea why sometimes the FullTextContent property in the index is not filled in?
Already tried re-indexing but that didn't fix the problem.
We don't have any errors in our logs either.

**Comment by skttl** [comment]
How are you reindexing?

**Comment by Sven883** [comment]
Hello Skttl, 
I'm reindexing by using the 'reindex nodes' button in the full text search package.

**Comment by Sven883** [comment]
Extra information: I'm using v1.2.1-Beta since we need the document type filter.
The FullTextSearch property in the index is only empty on document type 'NewsItem'.
That newsItem page & parent page is rendering correctly without any errors. But the property is still empty in the index:
![image](https://user-images.githubusercontent.com/77729251/118469740-4af21d00-b706-11eb-9da4-e2fe7ea7f954.png)

**Comment by skttl** [comment]
That sounds weird, are you doing anything special on your newsitems?

**Comment by Sven883** [comment]
@skttl  - I've found the issue. It had to do with a null value when fullTextSearch package was re-indexing that page.
Problem solved now. Thanks!

**Comment by skttl** [comment]
So something in your implementation? Could the details be useful for other users?

**Comment by Sven883** [comment]
Indeed something in our implementation.
