### ISSUE TITLE
Error after saving "Advanced Settings" in dashboard

### ISSUE THREAD

**Issue by alexroode** [skttl/umbraco-fulltextsearch8#61]
After opening "Advanced Settings" and saving in the Dashboard, I get the following parsing exception from Lucene when I try to search from within the dashboard.

`Cannot parse '( ((nodeName:test~0.8^10 OR nodeName_en-US:test~0.8^10) (FullTextContent:test~0.8 OR FullTextContent_en-US:test~0.8) ) ) AND (__NodeTypeAlias:) AND (__IndexType:content AND ((__VariesByCulture:y AND __Published_en-US:y) OR (__VariesByCulture:n AND __Published:y))) AND -(__NodeTypeAlias:searchPage) AND -(umbracoSearchHide_en-US:1 OR umbracoSearchHide:1) AND -(templateID:0)': Encountered " ")" ")`

The culprit appears to be the empty `__NodeTypeAlias:` filter.

It appears the frontend JS is sending an empty string in an array for `AllowedContentTypes` parameter, even though I've left the AllowedContentTypes untouched.

![fts0](https://user-images.githubusercontent.com/7908274/118749705-ed97c200-b812-11eb-8bec-2654f89fba5c.jpg)

If I supply a value for an allowed content type, the issue does not occur. 

It seems any empty text fields under Allowed Content Types leads to this issue. And because you can't delete the first AllowedContentType field,  you always run into this issue if you try to save the advanced settings without any AllowedContentType.

**Comment by skttl** [comment]
Hey @alexroode 

Thanks for the thorough description, I'll look into it later, if you can't wait, and can fix it yourself, feel free to submit a PR :)
