### ISSUE TITLE
Reindex selected nodes with descendants

### ISSUE THREAD

**Issue by LadislavAmbrus** [skttl/umbraco-fulltextsearch8#69]
Hi, there are two issues with reindexing selected nodes with descendants, causing "Include descendants" not working at all.
1. in fulltextsearch.resource.js, there is missing equals sign here:
                   ` nodeIds + "&includeDescendants=true";`
2. in IndexControlles.cs and its ReIndexNodes method, I believe index.IndexItems method should be called with ids of descendants, not just parent node. And those descendants should by get by specifying culture, because without it Umbraco returns descendants only for one culture. It could be done by iterating node.Cultures.

I am addressing 1.x version, but first issue seems to be in 2.x as well.

**Comment by skttl** [comment]
Thanks for reporting this. Any chance you can do a PR?

**Comment by LadislavAmbrus** [comment]
I did this: https://github.com/skttl/umbraco-fulltextsearch8/pull/70
It was first time for me to do a PR. I hope I did it right.

**Comment by skttl** [comment]
Fixed in 2.1 - don't want to support 1.x anymore.
