### ISSUE TITLE
Full Text Search permanently disabled

### ISSUE THREAD

**Issue by craigs100** [skttl/umbraco-fulltextsearch8#72]
Umb 9.2.0 with FTSfU V2.0.0.0 installed on a site with 450 pages and 2,800 docs in it's External Index.

Using the method described in the docs for a simple Razor search there are no results returned at all.  The same term in the External Index search in the Examine Manager returns 42 results. Below is the code used and a screenshot of the Full Text Search UI in Umbraco (which I found by accident as it's not mentioned in the docs ;) ).  I've tried setting o.Enabled = true and false and not there at all. All give no results. Is this compatible with Umbraco V9.2.0?

Code:-
```
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage
@inject Our.Umbraco.FullTextSearch.Helpers.FullTextSearchHelper FullTextSearchHelper

@{
  Layout = "Master.cshtml";  
  var searchQuery = Context.Request.Query["q"];
}

<div>
  <article>
    <h2>Search</h2>
    <form action="" method="GET">
      <input type="text" name="q" placeholder="Search" value="" />
      <input type="submit" value="Search" />
    </form>
    @if (!string.IsNullOrWhiteSpace(searchQuery))
    {
      var searchResult = FullTextSearchHelper.Search(searchQuery);
      var resultCount = searchResult.TotalResults;

        @if (resultCount > 0)
        {
          <div>
            <p>We found <strong>@resultCount</strong> result@(resultCount != 1 ? "s" : "") when searching for <strong>@searchQuery</strong></p>
          </div>

          <div>
            @foreach (var result in searchResult.Results)
            {
                <div>
                  <a href="@result.Content.Url()">@result.Title</a>
                  <p>
                      @result.Summary
                  </p>
                  <small>
                      Url: @result.Content.Url()<br />
                      Id: @result.Id<br />
                      Last updated: @(result.Content.UpdateDate)<br />
                      Score: @result.Score
                  </small>
                </div>            
            }
          </div>
        }
        else
        {
          <div">
            <p>Sorry, but your search for <strong>"@searchQuery"</strong> did not match any results. Please try again.</p>
          </div>
        }
    }
  </article>
</div> 
```
Umbraco UI:-
![Screenshot from 2022-01-19 14-45-23](https://user-images.githubusercontent.com/1143883/150153832-175d124b-7448-42a9-855b-eb6565a9ada2.png)

Thanks.

**Comment by skttl** [comment]
Hi Craig

Found out it was a bug with the json serializing when sending the config to the dashboard.

And the default pagelength of the search result was 0  - that was why you didn't get any results.

Both these are fixed in the newly released 2.1.0 version https://www.nuget.org/packages/Our.Umbraco.FullTextSearch/2.1.0
