### ISSUE TITLE
Indexation problem

### ISSUE THREAD

**Issue by SvenGoormans** [skttl/umbraco-fulltextsearch8#73]
Hello!
We have a Umbraco v8.14.0 with fulltextsearch v1.3.0-beta setup on azure.

We noticed that after each deploy the fulltextseach index is not indexed properly.
Looking at the default external index provided by Umbraco we notice that this index is indexed properly.

The fulltextsearch index only works when we manually re-build the external index.

Any idea why?

We customized the external index valueSetValidator with the following code, but that shouldn't interfere with the indexation of the fulltextsearch index right?

```
public class CustomizeExternalIndexComposer : IUserComposer
    {
        public void Compose(Composition composition)
        {
            composition.RegisterUnique<IUmbracoIndexConfig, CustomIndexConfig>();
        }
    }

    public class CustomIndexConfig : UmbracoIndexConfig, IUmbracoIndexConfig
    {
        private IScopeProvider _scopeProvider;

        public CustomIndexConfig(IPublicAccessService publicAccessService, IScopeProvider scopeProvider) : base(publicAccessService)
        {
            _scopeProvider = scopeProvider;
        }

        IContentValueSetValidator IUmbracoIndexConfig.GetPublishedContentValueSetValidator()
        {
            var excludeItemTypes = Current.Services.ContentTypeService.GetAll().Where(x => !x.IsElement && !x.PropertyTypeExists("allowSearching"))?.Select(x => x.Alias) ?? null;

            return new ContentValueSetValidator(true, false, PublicAccessService, _scopeProvider, null, null, excludeItemTypes);
        }
    }
```

Thanks in advance!

**Comment by skttl** [comment]
Hi @SvenGoormans 

Did you try removing your CustomIndexConfig to verify that it's not interfering?

**Comment by SvenGoormans** [comment]
Hey @skttl, yes we even tried adding a custom external index component and use the initialize method:
`_indexRebuilder.RebuildIndex()`
