### ISSUE TITLE
Umbraco v9(9.4.3) - Cache/Rendering Issues - Possible conflict with uSync

### ISSUE THREAD

**Issue by lakesol** [skttl/umbraco-fulltextsearch8#74]
So this is a little odd and may need some explaining.

What I am seeing is that after application startup in my local environment that indexing is taking place.  I think this is caused by uSync setup to sync/import on startup.

`"uSync" : {
    "Sets" : {
      "default" : {
        "HandlerDefaults" : {
          "UseFlatStructure": false
        }
      }
    },
    "Settings": {
      "ImportAtStartup" : "Settings, Content, Forms" ,
      "UIEnabledGroups": "Settings, Content, Forms, Media"
    }
  }`

What then happens is that publication of the content is causing the index to be rebuilt, which is tern causes the FullTextSearch index cache to be refreshed.

The code here calls the pipelines to render the template;

`var fullHtml = _umbracoComponentRenderer.RenderTemplateAsync(publishedContent.Id).Result.ToString();
                var fullText = _htmlService.GetTextFromHtml(fullHtml);`

In order to render a template umbraco requires a HttpContext using the following extension;

![image](https://user-images.githubusercontent.com/5919075/162723855-879c2bf0-f50b-47aa-acf0-2556da2aba50.png)

![image](https://user-images.githubusercontent.com/5919075/162723965-ac9e1bb7-cf23-4e38-a59e-2d5ec90ff9ee.png)

However, there can be a timing issue/race condition on the startup which results in httpContextAccessor.HttpContext returning null and thus the render generates an error in the html.  When GetTextFromHtml is called on this response the output is an empty string.

This in turn then gets written into the cache DB as follows;

![image](https://user-images.githubusercontent.com/5919075/162720248-d64d5651-74e5-4133-b1bc-354301a049eb.png)

Node 1087 is the home page node.  FYI all nodes in the cache DB end up with content when a rebuild index is carried out within the full text search plugin.

Can you suggest how this issue may be mitigated, as it results in search queries not returning expected results after application startup?

Many thanks
Lake

**Comment by skttl** [comment]
Hi @lakesol 

Maybe we could exit early if HttpContext is null in https://github.com/skttl/umbraco-fulltextsearch8/blob/master/src/Our.Umbraco.FullTextSearch/Services/CacheService.cs#L49?

What do you think?

**Comment by skttl** [comment]
Hi @lakesol 

I've been trying to recreate in v12 (with FullTextSearch 4.0.0-alpha001) with no luck. When the indexing kicks it doesn't even try to render the pages. But anyway, the cache table is filled whenever a page is published, so I can't imagine how you can get to a situation where you have pages in your solution, but no examine index AND no cache table content.

Feel free to reopen with any comments. But do try it out in the latest alpha and v12, just to be sure we are not chasing something thats already been fixed.

**Comment by lakesol** [comment]
Hi @skttl 

I agree, it may have been mitigated in later versions of Umbraco, from memory this was in a version 9 build.

A little while ago this project migrated away from on-prem to Umbraco cloud, and as such we moved from uSync to Umbraco Deploy.  We have not seen any issues since that point.  So I think close this now unless anyone else finds the same issue.

Thanks for taking the time to investigate.
