### ISSUE TITLE
SearchQueries with multiple terms are slow

### ISSUE THREAD

**Issue by Sven883** [skttl/umbraco-fulltextsearch8#77]
Hello!

We're using Our.Umbraco.FullTextSearch v1.3.0-beta with an Umbraco v8.14.1 installation.
We're using this package for a while now, and we notice that queries with multiple terms are way slower.

Queries can sometimes take up to 30 seconds to complete, comparing to >1second for a single term.

This is our search object that we use:
`{"Culture":"nl","SearchType":0,"SearchTerm":"Verankering van","TitleProperties":["nodeName"],"TitleBoost":10.0,"BodyProperties":["FullTextContent"],"SummaryProperties":[],"RootNodeIds":[],"SummaryLength":300,"PageLength":5,"Fuzzyness":0.8,"AddWildcard":true,"HighlightSearchTerms":false,"AllowedContentTypes":["tool"],"SearchTermQuoted":[""Verankering van""],"SearchTermSplit":["Verankering van"]}`

**Comment by Sven883** [comment]
Hey @skttl, this issue has been created a while ago.
Would you be able to take a look at it please?

Thanks in advance!

**Comment by skttl** [comment]
You are welcome to take a shot yourself.

**Comment by Sven883** [comment]
Alright thanks!

**Comment by Sven883** [comment]
@skttl I've found the issue using profilingLogger.
I've noticed that the code line: 
result.TotalResults = results.TotalItemCount; 
slows down the query by alot.

No idea yet how to solve this.

**Comment by Sven883** [comment]
@skttl some more information:
- Examine dll: v1.2.2.0
- Lucene dll: 3.0.3.0

Would upgrading examine/lucene help at all?

**Comment by skttl** [comment]
Hi @Sven883 

I think that might be a problem in Examine or Lucene, as the `TotalItemCount` property is coming from Examine.

Can you upgrade (is there even any upgrades compatible with Umbraco 8?) and see if that helps?
