### ISSUE TITLE
Make highlight element type configurable

### ISSUE THREAD

**Issue by enkelmedia** [skttl/umbraco-fulltextsearch8#82]
Hi (again) =D

Got a request if we could change the `<b>` element into a `<mark>` and noticed that this is hard coded here:

https://github.com/skttl/umbraco-fulltextsearch8/blob/0429fccdd49ff50cc4f3ddff7bed25208dcbca7c/src/Our.Umbraco.FullTextSearch/Services/SearchService.cs#L367

What do you say about making this a option and add this to the `FullTextSearchOptions`? 

Again, I would be happy to create a PR =D

**Comment by skttl** [comment]
Sounds like a good idea, maybe it should be in the form of a format like `<b>%0</b>`, then you could override the config with `<mark>%0</mark>` or `<span class="font-bold">%0</span>` etc.

**Comment by enkelmedia** [comment]
Solved in this merge: https://github.com/skttl/umbraco-fulltextsearch8/pull/84
