### ISSUE TITLE
Add unit test project?

### ISSUE THREAD

**Issue by enkelmedia** [skttl/umbraco-fulltextsearch8#85]
When working on https://github.com/skttl/umbraco-fulltextsearch8/issues/82 I made some unit test outside of the project to make sure things did not break but I didn't want to include it in that PR so hence creating this issue.

Would you be open to adding a unit test project?

If yes, I would be happy to add the stuff that I made "on the side" in PR. I was using NUnit but if you have another preference I' happy to adjust in the PR.

Cheers!

**Comment by skttl** [comment]
Very much open to adding testing - so PR away :)

**Comment by enkelmedia** [comment]
Added in the PR it self to avoid merge problems =D

https://github.com/skttl/umbraco-fulltextsearch8/pull/84
