### ISSUE TITLE
v4 - Back-office Search dashboard error when choosing "Advanced Settings" option

### ISSUE THREAD

**Issue by hfloyd** [skttl/umbraco-fulltextsearch8#89]
Hi! I tested a search with the FTS dashboard, and it returned a result. But when I then set some "Advanced Options" (just adding an additional field to the "body properties" list), the search returned an error:
![image](https://github.com/skttl/umbraco-fulltextsearch8/assets/1252593/d6638a57-11f5-4056-82ea-f02e7ed4d705)

Setting a debugger on the source code, it shows the point where the exception occurs:
![image](https://github.com/skttl/umbraco-fulltextsearch8/assets/1252593/5165e2e3-73f6-495a-bd82-6bbc0aadb06c)

Which is odd, since there IS a search term specified in the UI. But perhaps it isn't getting to the controller correctly?

**Comment by skttl** [comment]
Fixed in a34d1ef - thanks for reporting!
