### ISSUE TITLE
Block grid JSON appearing in summary text

### ISSUE THREAD

**Issue by richarth** [skttl/umbraco-fulltextsearch8#91]
We have a block grid bodyText property on a doc type.  I've configured the search class and added the bodyText property to the body and summary search properties.

When you perform a search, for a few results the summary field is showing some of the block grid JSON.

I've inspected one of the pages where this is happening and the bodyText value is as follows in case it helps:

`[{"name":"Home","url":"google.com"}] ["Purple"] Button 1 {"icon":"fa-chevron-right","packageId":"e6b21e81-1051-46df-b7a2-d72af77892eb"} [{"name":"google","url":"google.com"}] ["Turquoise"] Button 2 {"icon":"fa-chevron-right","packageId":"e6b21e81-1051-46df-b7a2-d72af77892eb"} [{"name":"Home","url":"google.com"}] ["Purple"] Button 1 {"icon":"fa-chevron-right","packageId":"e6b21e81-1051-46df-b7a2-d72af77892eb"} [{"name":"google","url":"google.com"}] ["Turquoise"] Button 2 {"icon":"fa-chevron-right","packageId":"e6b21e81-1051-46df-b7a2-d72af77892eb"} 1 Test`

I've tested this v3.1.0 and v4.0.0-alpha001

**Comment by skttl** [comment]
Hi @richarth 

Thanks for trying out the package. If you have a JSON based property in bodyText, and set that as a summary field, Full Text Search will try to generate a summary from that, making it show the JSON. This is expected. Instead you should use the FullTextContent property instead, maybe combined with (if you have it) a metaDescription property or similar.

**Comment by richarth** [comment]
Hi @skttl,

Thanks for the assistance.  I switched to the FullTextContent property and that solved it thanks.  The package was doing a great job creating a summary for the vast majority of the pages when I had my bodyText field as the summary.

Thanks also for the fantastic package.  It really makes creating a site search a breeze.
