### ISSUE TITLE
Consider changing SQL server field type from ntext to nvarchar(max)?

### ISSUE THREAD

**Issue by hfloyd** [skttl/umbraco-fulltextsearch8#94]
As per [Microsoft](https://learn.microsoft.com/en-us/sql/t-sql/data-types/ntext-text-and-image-transact-sql?view=sql-server-ver15):

> The ntext, text, and image data types will be removed in a future version of SQL Server. Avoid using these data types in new development work, and plan to modify applications that currently use them. Use [nvarchar(max)](https://learn.microsoft.com/en-us/sql/t-sql/data-types/nchar-and-nvarchar-transact-sql?view=sql-server-ver15), [varchar(max)](https://learn.microsoft.com/en-us/sql/t-sql/data-types/char-and-varchar-transact-sql?view=sql-server-ver15), and [varbinary(max)](https://learn.microsoft.com/en-us/sql/t-sql/data-types/binary-and-varbinary-transact-sql?view=sql-server-ver15) instead.

Should the SQL table be updated here?

**Comment by skttl** [comment]
If Microsoft says so, we better adjust :)

Great candidate for a new major too!

**Comment by skttl** [comment]
Fixed in d851e7f :)
