### ISSUE TITLE
Index locking issue

### ISSUE THREAD

**Issue by nilaydigiwhiz** [skttl/umbraco-fulltextsearch8#95]
Hi,

I am using this plugin on one of our websites. This site is hosted on the Azure Web app and a single instance has two sites running 

We have applied all suggested solutions from Umbraco to set up site on Azure but we are still having issue where indes is getting locked after sometime 

Is there anything this plugin doing which locks the index? something i need to update to run a search using this plugin on azure?

Here is the error

ystem.ApplicationException: Could not create an index searcher with the supplied lucene directory ---> System.IO.FileNotFoundException: 0.cfs ---> System.IO.FileNotFoundException: Could not find file 'D:\home\site\wwwroot\AppData\TEMP\ExamineIndexes\External_0.cfs'. at Examine.LuceneEngine.Directories.SyncIndexInput.SyncLocally(String fileName) in D:\a\1\s\src\Examine\LuceneEngine\Directories\SyncIndexInput.cs:line 182 at Examine.LuceneEngine.Directories.SyncIndexInput..ctor(SyncDirectory directory, String name, ILoggingService loggingService) in D:\a\1\s\src\Examine\LuceneEngine\Directories\SyncIndexInput.cs:line 98 at Examine.LuceneEngine.Directories.SyncDirectory.OpenInput(String name) in D:\a\1\s\src\Examine\LuceneEngine\Directories\SyncDirectory.cs:line 248 --- End of inner exception stack tra

**Comment by skttl** [comment]
You shouldn't do anything specific for this package. Looks like something might be wrong in your setup, but I believe it has nothing to do with Full Text Search. Does the file for the internal index exist?

**Comment by nilaydigiwhiz** [comment]
Ya file exist but it gets locked

**Comment by skttl** [comment]
Closing this,
